<#! 
.SYNOPSIS
  Render the structured build report as CLI text or HTML.
##>
param(
    [Parameter(Mandatory)][string]$ReportPath,
    [ValidateSet('Cli','Html')][string]$Format = 'Cli',
    [string]$OutputPath
)

$report = Get-Content -LiteralPath $ReportPath -Raw -Encoding UTF8 | ConvertFrom-Json

function Rows($items) { @($items | Where-Object { $null -ne $_ }) }
function HtmlCell([object]$value) { [System.Net.WebUtility]::HtmlEncode([string]$value) }
function StatusClass([object]$item) {
    $status = [string]$item.Status
    if ($status -match '^(OK|WINNER|CACHE)$') { return 'ok' }
    if ($status -match '^(EMPTY|API_MISSING|PARSE_ERROR|DOWNLOAD_ERROR|RequestError|\d+)') { return 'bad' }
    return ''
}
function StatusRank([object]$item) {
    $status = [string]$item.Status
    if ($status -match '^(404|5\d\d|RequestError|DOWNLOAD_ERROR|PARSE_ERROR|API_MISSING|EMPTY)') { return 0 }
    if ($status -match '^(WARN|WARNING|FILTERED)') { return 1 }
    return 2
}
function HtmlTable([string[]]$Headers, [object[]]$Items, [scriptblock]$Values) {
    $head = ($Headers | ForEach-Object { '<th>' + (HtmlCell $_) + '</th>' }) -join ''
    $body = foreach ($item in (Rows $Items | Sort-Object @{Expression={ StatusRank $_ }; Ascending=$true})) {
        $cells = & $Values $item | ForEach-Object { '<td>' + (HtmlCell $_) + '</td>' }
        '<tr class="' + (StatusClass $item) + '">' + ($cells -join '') + '</tr>'
    }
    return '<table><thead><tr>' + $head + '</tr></thead><tbody>' + ($body -join '') + '</tbody></table>'
}

if ($Format -eq 'Cli') {
    Write-Output '=== Structured build report ==='
    foreach ($section in @('Sources','Deduplication','ApiResolution','ZipFallback','OfficialExclusions','Outputs')) {
        $items = Rows $report.$section
        if ($items.Count -eq 0) { continue }
        Write-Output ""
        Write-Output ("[$section]")
        $items | ConvertTo-Csv -NoTypeInformation | Write-Output
    }
    if ($report.Summary) {
        Write-Output ""
        Write-Output '[Summary]'
        $report.Summary | ConvertTo-Json -Depth 10 | Write-Output
    }
    exit 0
}

$parts = @('<!doctype html><html><head><meta charset="utf-8"><style>body{font:14px sans-serif;color:#222}h1{font-size:22px}h2{font-size:17px;margin-top:24px}h3{font-size:15px;margin:12px 0 4px}table{border-collapse:collapse;margin:8px 0 18px;width:100%}th,td{border:1px solid #ccc;padding:4px 8px;text-align:left;vertical-align:top}th{background:#f1f3f5}.ok{color:#176b35;background:#effaf2}.bad{color:#a61b1b;background:#fff0f0}.muted{color:#666}.nested{margin-left:20px;width:calc(100% - 20px)}</style></head><body>')
$parts += '<h1>DalamudRepo build report</h1>'
$parts += '<p>Structured report generated by <code>CreateReport.ps1</code>.</p>'
$parts += '<h2>Stage 1: Source collection</h2>'
$parts += HtmlTable @('Status','Candidates','Source') $report.Sources { param($x) @($x.Status,$x.Count,$x.Url) }
$parts += '<h2>Stage 2: Deduplication</h2>'
$parts += '<table><thead><tr><th>Plugin</th><th>Winner (Version / Source)</th><th>Dropped candidates (Version / Source)</th></tr></thead><tbody>'
foreach ($d in (Rows $report.Deduplication | Sort-Object Plugin)) {
    $winner = if ($d.Winner -is [string]) { [pscustomobject]@{ Version = ''; Url = $d.Winner } } else { $d.Winner }
    $winnerHtml = '<span class="ok">' + (HtmlCell $winner.Version) + '</span><br>' + (HtmlCell $winner.Url)
    $candidateHtml = (@($d.Candidates | Where-Object { $_.Status -ne 'WINNER' } | ForEach-Object {
        if ($_ -is [string]) { HtmlCell $_ } else { (HtmlCell $_.Version) + '<br>' + (HtmlCell $_.Url) }
    }) -join '<br><hr>')
    $parts += '<tr><td>' + (HtmlCell $d.Plugin) + '</td><td>' + $winnerHtml + '</td><td>' + $candidateHtml + '</td></tr>'
}
$parts += '</tbody></table>'
$parts += '<h2>Stage 2b: Version and API resolution</h2>'
$parts += HtmlTable @('Plugin','Stable API','Testing API') $report.ApiResolution { param($x) @($x.Plugin,$x.DalamudApiLevel,$x.TestingDalamudApiLevel) }
$parts += '<h2>Stage 2c: Zip fallback</h2>'
$parts += HtmlTable @('Plugin','Status','API','URL') $report.ZipFallback { param($x) @($x.Plugin,$x.Status,$x.Api,$x.Url) }
$parts += '<h2>Stage 2d: Official plugin exclusions</h2>'
foreach ($source in (Rows $report.OfficialExclusions | Group-Object SourceFile | Sort-Object Name)) {
    $parts += '<h3>' + (HtmlCell $source.Name) + ' <span class="muted">(' + $source.Count + ' plugins)</span></h3>'
    foreach ($repo in ($source.Group | Group-Object RepositoryUrl | Sort-Object Name)) {
        $parts += '<details><summary>' + (HtmlCell $repo.Name) + ' (' + $repo.Count + ')</summary>'
        $parts += '<table class="nested"><thead><tr><th>Plugin</th></tr></thead><tbody>'
        foreach ($plugin in ($repo.Group | Sort-Object InternalName)) {
            $parts += '<tr class="bad"><td>' + (HtmlCell $plugin.InternalName) + '</td></tr>'
        }
        $parts += '</tbody></table></details>'
    }
}
$parts += '<h2>Stage 3: Build outputs</h2>'
$parts += HtmlTable @('Output','Entries','Status') $report.Outputs { param($x) @($x.Name,$x.Count,$x.Status) }
$parts += '<h2>Stage 4: Summary</h2><pre>' + (HtmlCell (($report.Summary | ConvertTo-Json -Depth 10))) + '</pre>'
$parts += '</body></html>'
$html = $parts -join "`n"
if ($OutputPath) { Set-Content -LiteralPath $OutputPath -Value $html -Encoding UTF8 } else { Write-Output $html }
