<#! 
.SYNOPSIS
  Render the structured build report as CLI text or HTML.
##>
param(
    [Parameter(Mandatory)][string]$ReportPath,
    [ValidateSet('Cli','Html')][string]$Format = 'Cli',
    [string]$OutputPath
)

$report = Get-Content -LiteralPath $ReportPath -Raw -Encoding UTF8 | ConvertFrom-Json

function Rows($items) { @($items | Where-Object { $null -ne $_ }) }
function HtmlCell([object]$value) { [System.Net.WebUtility]::HtmlEncode([string]$value) }
function HtmlTable([string[]]$Headers, [object[]]$Items, [scriptblock]$Values) {
    $head = ($Headers | ForEach-Object { '<th>' + (HtmlCell $_) + '</th>' }) -join ''
    $body = foreach ($item in (Rows $Items)) {
        $cells = & $Values $item | ForEach-Object { '<td>' + (HtmlCell $_) + '</td>' }
        '<tr>' + ($cells -join '') + '</tr>'
    }
    return '<table><thead><tr>' + $head + '</tr></thead><tbody>' + ($body -join '') + '</tbody></table>'
}

if ($Format -eq 'Cli') {
    Write-Output '=== Structured build report ==='
    foreach ($section in @('Sources','Deduplication','ApiResolution','ZipFallback','OfficialExclusions','Outputs')) {
        $items = Rows $report.$section
        if ($items.Count -eq 0) { continue }
        Write-Output ""
        Write-Output ("[$section]")
        $items | ConvertTo-Csv -NoTypeInformation | Write-Output
    }
    if ($report.Summary) {
        Write-Output ""
        Write-Output '[Summary]'
        $report.Summary | ConvertTo-Json -Depth 10 | Write-Output
    }
    exit 0
}

$parts = @('<!doctype html><html><head><meta charset="utf-8"><style>body{font:14px sans-serif;color:#222}h1{font-size:22px}h2{font-size:17px;margin-top:24px}table{border-collapse:collapse;margin:8px 0 18px}th,td{border:1px solid #ccc;padding:4px 8px;text-align:left;vertical-align:top}th{background:#f1f3f5}.ok{color:#176b35}.bad{color:#a61b1b}</style></head><body>')
$parts += '<h1>DalamudRepo build report</h1>'
$parts += '<p>Structured report generated by <code>CreateReport.ps1</code>.</p>'
$parts += '<h2>Source status</h2>'
$parts += HtmlTable @('Status','Candidates','Source') $report.Sources { param($x) @($x.Status,$x.Count,$x.Url) }
$parts += '<h2>Zip fallback</h2>'
$parts += HtmlTable @('Plugin','Status','API','URL') $report.ZipFallback { param($x) @($x.Plugin,$x.Status,$x.Api,$x.Url) }
$parts += '<h2>Official plugin exclusions</h2>'
$parts += HtmlTable @('Source','Plugin') $report.OfficialExclusions { param($x) @($x.Source,$x.InternalName) }
$parts += '<h2>Outputs</h2>'
$parts += HtmlTable @('Output','Entries','Status') $report.Outputs { param($x) @($x.Name,$x.Count,$x.Status) }
$parts += '<h2>Summary</h2><pre>' + (HtmlCell (($report.Summary | ConvertTo-Json -Depth 10))) + '</pre>'
$parts += '</body></html>'
$html = $parts -join "`n"
if ($OutputPath) { Set-Content -LiteralPath $OutputPath -Value $html -Encoding UTF8 } else { Write-Output $html }
